spring:
  application:
    name: "sistema_solar_restapi"

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/dawiapp?useSSL=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:cancer16}
    driver-class-name: com.mysql.cj.jdbc.Driver

  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:9a8b7c6d5e4f3g2h1i0j9k8l7m6n5o4p3q2r1s0t}
      expiration: ${JWT_EXPIRATION:60}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:300}

server:
  port: ${SERVER_PORT:8080}
